### ISSUE TITLE
Uncaptured server errors on 404

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#114]
It looks like right now the server reports 404's on the console. Sometimes like this (http://localhost:3000/category/performance/):
```
An error ocurred fetching '/category/mobile-performance/':
 Error: Entity of from endpoint 'categories' with slug 'mobile-performance' not found
    at Api.getIdBySlug (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/api.ts:9:227)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
and sometimes like this (http://localhost:3000/page/8):
```
An error ocurred fetching '/':
 TypeError: Cannot destructure property `id` of 'undefined' or 'null'.
    at entityList.map (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/populate.ts:6:47)
    at Array.map (<anonymous>)
    at populate (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/populate.ts:6:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by orballo** [comment]
Fixed in https://github.com/frontity/frontity/pull/122

**Comment by luisherranz** [comment]
This is still happening in the current version. Both errors:

http://localhost:3000/category/asdf/:
```
Error: Entity of from endpoint 'categories' with slug 'asdf' not found
    at Api.getIdBySlug (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/api.ts:9:227)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

and http://localhost:3000/asdf:
```
TypeError: Cannot destructure property `id` of 'undefined' or 'null'.
    at attachmentHandler (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/attachment.ts:4:135)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

@DAreRodz could you please document here why is this happening and what can we do about it?

**Comment by SantosGuillamot** [comment]
It also happens in these urls, both with the same error:

http://localhost:3000/category/chastening
http://localhost:3000/category/disinfection

```
TypeError: Cannot read property 'name' of undefined
      at List (webpack-internal:///./packages/mars-theme/src/components/list/list.js:10:271)
      at runAsReaction (webpack-internal:///./node_modules/@frontity/connect/src/reactionRunner.js:16:45)
      at reaction (webpack-internal:///./node_modules/@frontity/connect/src/observer.js:7:131)
      at props (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:18:8)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:452:2364)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:451:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:487:855)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:487:55)
      at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:520:116)
      at app.use (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:47:243)
```

**Comment by orballo** [comment]
It looks like the cause is this `console.log`
https://github.com/frontity/frontity/blob/bd8c6dc3d9872f1780e395c952737c867c88c0e8/packages/wp-source/src/actions.ts#L49

Introduced in this [commit](https://github.com/frontity/frontity/commit/0b877b2e302ff60749a605302e5b48b544802164) about a month ago.

**Comment by luisherranz** [comment]
That's the cause of the console log but we need to know what's making it throw in the first place. Both:
```bash
TypeError: Cannot destructure property `id` of 'undefined' or 'null'.
// and
TypeError: Cannot read property 'name' of undefined
```

@DAreRodz could you please document here why is this happening and what can we do about it?

**Comment by DAreRodz** [comment]
Those errors must be in handlers. I'm checking which of them need to be fixed.

**Comment by DAreRodz** [comment]
**First case:** ```Cannot destructure property `id` of 'undefined' or 'null'```

[Attachment](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/attachment.ts#L26) and [Page](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/page.ts#L19) handlers could throw that error when the attachment or page is not found.

Also,  [Author](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/author.ts#L23L25), [Date](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/date.ts#L37L39), [Taxonomy](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/taxonomy.ts#L33L35) and [PostArchive](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/postArchive.ts#L17L19) handlers should throw a descriptive error when a page out of range is fetched, but are not implemented correctly, returning the error above. They all fail at [this line](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/populate.ts#L40) in `populate.ts`.

The reason is that `api.get` returns the following error object and `populate` doesn't know how to handle it:
```json
{
    "code": "rest_post_invalid_page_number",
    "message": "The page number requested is larger than the number of pages available.",
    "data": {
        "status": 400
    }
}
```

**Comment by DAreRodz** [comment]
**Second case:** ```Cannot read property 'name' of undefined```

This error is happening at [this line](https://github.com/frontity/frontity/blob/dev/packages/mars-theme/src/components/list/list.js#L15) in the `List` component. The problem here is the limit of 10 categories maximum when embedding. `Taxonomy` handler was assuming that the category being fetched would appear in the embedded categories of the posts, and this is not the case. The category is not being populated and `List` fails when it renders.

In the case of `chastening` category (id: 74), it contains just one post with 64 categories, and that post has the id `74` at the index `10` inside `categories` array.

**Comment by orballo** [comment]
But I think those errors are expected by design. It's a try catch that when the error is thrown in the handler sets `is404: true`, unless any of the URL failing should work instead, is not actually a bug.

**Comment by DAreRodz** [comment]
Yeah, well, most cases are expected to return with a `404` page but not all of them (for example, when the server returns a `500` error). And it would also be nice if the error messages were more descriptive for developers.

We have to think of a good way to handle errors.

**Comment by orballo** [comment]
Yeah, that totally makes sense. It just seems to be something different than the original meaning of this issue.

**Comment by orballo** [comment]
Yeah, that makes sense.

**Comment by luisherranz** [comment]
Closed as this doesn't seem to be an issue anymore.
